FROM gcc:4.9

RUN apt-get update && apt-get install -y swi-prolog
RUN apt-get update && apt-get install -y clisp
RUN apt-get update && apt-get install -y openjdk-7-jre
RUN apt-get update && apt-get install -y openjdk-7-jdk
RUN apt-get update && apt-get install -y git
RUN apt-get update && apt-get install -y vim
RUN apt-get update && apt-get install -y rsync

